name: Get Wikidata info

on:
  schedule:
    - cron:  '24 1 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - name: Install dependencies
      run: |-
        sudo apt-get install jq moreutils
        npm install -g wikibase-cli
    - name: Get list of historic cabinets
      run: wd sparql sparql/all-cabinets.sparql -f csv | sed -e 's#http://www.wikidata.org/entity/##g' | ifne tee wikidata/all-cabinets.csv
    - name: Get list of minister positions
      run: wd sparql sparql/minister-positions.sparql -f csv | sed -e 's#http://www.wikidata.org/entity/##g' | ifne tee wikidata/minister-positions.csv
    - name: Get list of all ministers
      run: wd sparql sparql/all-ministers.sparql -f csv > /tmp/AMS && sed -e 's#http://www.wikidata.org/entity/##g' /tmp/AMS | ifne tee wikidata/all-ministers.csv
    - name: Commit and push if changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add wikidata
        timestamp=$(date -u)
        git commit -m "refresh wikidata JSON: ${timestamp}" || exit 0
        git push
