name: Get Wikidata info

on:
  schedule:
    - cron:  '30 7 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - run: npm ci --no-audit
    - run: npm test
    - name: Install wikibase-cli
      run: npm install -g wikibase-cli
    - name: Run SPARQL
      run: wd sparql cabinet-list.sparql > cabinet-list.json
    - name: Commit and push if changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add cabinet-list.json
        timestamp=$(date -u)
        git commit -m "Update wikidata JSON: ${timestamp}" || exit 0
        git push
